# Generated by Django 4.2.5 on 2023-09-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_group_student_id_alter_group_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
