# Generated by Django 4.2.5 on 2023-09-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_group_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Belt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="belt_status",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="user.belt"
            ),
        ),
    ]
