# Generated by Django 4.2.5 on 2023-09-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_student_belt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="rating_points",
            field=models.IntegerField(),
        ),
    ]
