# Generated by Django 4.2.5 on 2023-09-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_student_rating_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="absence_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="injury_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="presence",
            field=models.IntegerField(default=0),
        ),
    ]
