# Generated by Django 4.2.5 on 2023-10-07 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_student_rating_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="belt_status",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="user.belt"
            ),
        ),
    ]
