# Generated by Django 4.2.5 on 2023-10-01 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0007_student_absence_day_student_injury_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Название тренировки"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание тренировки")),
                (
                    "present_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Число присутствующих"
                    ),
                ),
                (
                    "absent_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Число отсутствующих"
                    ),
                ),
                (
                    "injured_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Число заболевших/травмированных"
                    ),
                ),
                (
                    "training_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.group"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                ("was_sick", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.student"
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.training",
                    ),
                ),
            ],
        ),
    ]
