# Generated by Django 4.2.5 on 2023-10-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="training_date",
            field=models.DateTimeField(),
        ),
    ]
